# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["desarrollo"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  # Single deploy job since we're just deploying
  mostrarMensaje:
    runs-on: ubuntu-latest

    steps:
      - name: 'Greeting'
        run: echo "Hello Github"
  
